update project

diff --git a/open b/open
--- a/open
+++ b/open
@@ -1,223 +1,184 @@
 #!/bin/bash
 
-main () {
-	run_here "$@"
-}
-
-run_here () {
-	dir=$1; shift
-	final_name=$1; shift
-	args="$@"
-	run $dir $dir/out $dir/prev $dir $dir/$final_name "$args"
-}
-
-run () {
-	in_dir=$1; shift
-	out_dir=$1; shift
-	prev_dir=$1; shift
-	exclude_dir=$1; shift
-	final_path=$1; shift
-	args="$@"
-	is_empty $final_path && {
-		explain
-		exit 1
-	}
-	ensure_dirs_exist $out_dir/ $prev_dir/ $exclude_dir/ $final_path
-	exclude_unchanged $in_dir $exclude_dir $prev_dir
-	compile_all $in_dir $out_dir
-	include_unchanged $exclude_dir $in_dir
-	link_to $final_path $out_dir
-	create_prev_files_of $in_dir $prev_dir
-	open $final_path $args
-}
-
-open () {
-	path=$1; shift
-	args="$@"
-	show "opening '$path' with '$args'..."
-	eval $path $args
-}
-
-create_prev_files_of () {
-	dir=$1; shift
-	prev_dir=$1
-	names=$(get_names_with_ext c $dir)
-	show "creating prev files of '$names'..."
-	for name in $names; {
-		prev_name=$(change_ext_to prev $name)
-		cp -f $dir/$name $prev_dir/$prev_name
-	}
-}
-
-link_to () {
-	final_path=$1; shift
-	dir=$1
-	paths=$(get_paths_with_ext o $dir)
-	show "linking '$(eval echo $paths)' to '$final_path'..."
-	gcc -Wall -g $paths -o $final_path
-	succeed=$?
-	! (exit $succeed) && {
-		explain
-		exit 2
-	}
-}
-
-compile_all () {
-	dir=$1; shift
-	out_dir=$1
-	names=$(get_names_with_ext c $dir)
-	show "compiling '$(eval echo $names)'..."
-	for name in $names; {
-		out_name=$(change_ext_to o $name)
-		compile $dir/$name $out_dir/$out_name
-	}
-}
-
-compile () {
-	path=$1; shift
-	out_path=$1
-	gcc -c -Wall -g $path -o $out_path
-	succeed=$?
-	! (exit $succeed) && {
-		explain
-		exit 3
-	}
-}
-
-include_unchanged () {
-	exclude_dir=$1; shift
-	dir=$1
-	exclude_names=$(get_names_with_ext exclude $exclude_dir)
-	show "including '$exclude_names' to '$dir'..."
-	for exclude_name in $exclude_names; {
-		name=$(change_ext_to c $exclude_name)
-		mv $exclude_dir/$exclude_name $dir/$name
-	}
-}
-
-exclude_unchanged () {
-	dir=$1; shift
-	exclude_dir=$1; shift
-	prev_dir=$1
-	names=$(get_names_with_ext c $dir)
-	show "getting unchanged from '$names'..."
-	unchanged_names=$(get_unchanged_from $dir $prev_dir)
-	show "excluding '$unchanged_names' from '$dir'..."
-	for name in $unchanged_names; {
-		exclude_name=$(change_ext_to exclude $name)
-		mv $dir/$name $exclude_dir/$exclude_name
-	}
-}
-
-ensure_dirs_exist () {
-	paths="$@"
-	dirs=$(echo $paths | sed -r '{
-		s/ +/\n/g
-	}' | sed -r '{
-		s/\/[^/]*$/\//g
-	}')
-	show "ensuring '$(eval echo $dirs)' exist..."
-	mkdir -p $dirs
-}
-
-get_unchanged_from () {
-	dir=$1; shift
-	prev_dir=$1
-	names=$(get_names_with_ext c $dir)
-	unchanged_names=
-	for name in $names; {
-		prev_name=$(change_ext_to prev $name)
-		difference=$(get_diff_of $dir/$name $prev_dir/$prev_name)
-		! is_empty $difference && {
-			continue
-		}
-		unchanged_names+="$name "
-	}
-	echo $unchanged_names
-}
-
-get_diff_of () {
-	path=$1; shift
-	diff_path=$1
-	echo $(diff --new-file $path $diff_path)
-}
-
-explain () {
-cat << "EOF"
-Usage: open [in_dir] [out_dir] [final_path] [args...]
-
-	in_dir
-		The directory of c files
-	out_dir
-		The directory of o files
-	final_path
-		The path to link the o files to
-	args
-		The arguments to be used by the final path
+get_open_config () {
+	cat << EOF | with_common_indent 0
+		TARGET="main"
+		EXECUTABLE_EXT="c"
+		CMAKE_MIN_VER="3.25"
+		CMAKE_LANGUAGE="C"
+		CMAKE_LANGUAGE_VER="1.0.0"
+		CXX_STD_VER="26"
+		IS_NCURSES=true
+		IS_FTXUI=false
+		FTXUI_VER=5
 EOF
 }
 
-get_names_with_ext () {
-	ext=$1; shift
-	dir=$1
-	ls $dir | tr " " "\n" | sed -r '{
-		/\.'"$ext"'$/!d
-	}'
-}
 
-get_paths_with_ext () {
-	ext=$1; shift
-	dir=$1
-	eval echo $dir/* | tr " " "\n" | sed '{
-		/\.'"$ext"'$/!d
-	}'
-}
-
-change_ext_to () {
-	ext=$1; shift
-	name=$1
-	echo $name | sed -r '{
-		s/\.[^./]*$/.'"$ext"'/
-	}'
-}
-
-show () {
-	str="$@"
-	fmt="\e[0;93m"
-	var_fmt="\e[1;96m"
-	noc="\e[m"
-	str=$(echo $str | sed -r "{
-		s/'([^']*)'/'\\$noc\\$var_fmt\1\\$noc\\$fmt'/g
-	}")
-	echo -e $fmt$str$noc
-}
-
-contains () {
-	substr=$1; shift
-	str="$@"
-	[[ $str =~ .*$substr.* ]] && {
+main () {
+	local dir="$1"
+	if [[ "$DONT_EXEC" == "true" ]]; then
 		return 0
+	fi
+	
+	local open_config_path="$dir/.open_config"
+	make_open_config "$open_config_path"
+	source "$open_config_path"
+	bat -l bash "$open_config_path"
+
+	local target="$TARGET"
+
+	if ! $IS_FTXUI; then
+		echo "Info: Not using FTXui"	
+	fi
+
+	get_cmake_lists_txt_str "$dir" "$target" > "$dir/CMakeLists.txt"
+	
+	mkdir -p "$dir/build"
+	cd "$dir/build"
+	cmake ..
+	make
+	./"$target"
+}
+
+get_cmake_lists_txt_str () {
+local dir="$1"
+local target="$2"
+cat << EOF | with_common_indent 0
+		cmake_minimum_required (VERSION $CMAKE_MIN_VER)
+		project($target LANGUAGES $CMAKE_LANGUAGE VERSION $CMAKE_LANGUAGE_VER)
+		$($IS_FTXUI && echo "find_package(ftxui $FTXUI_VER REQUIRED)")
+		$($IS_NCURSES && echo "add_compile_options(-lncurses)")
+		add_executable($target
+$({
+		find "$dir" -maxdepth 1 | 
+		sed "/\.$EXECUTABLE_EXT$/!d" | {
+			while read -r line; do
+				basename "$line"
+			done
+		} | with_common_indent 3
+})
+		)
+$([[ "$CMAKE_LANGUAGE" == "CXX" ]] && cat << EOF2 | with_common_indent 0
+		set_property(TARGET $target PROPERTY CXX_STANDARD $CXX_STD_VER)
+EOF2
+)
+$({
+	cat << EOF2 | with_common_indent 0 > "$dir/.clangd"
+		CompileFlags:
+$([[ "$CMAKE_LANGUAGE" == "C" ]] && {
+		cat << EOF3 | with_common_indent 1
+			Add: [-std=c99]
+EOF3
+	} || {
+		cat << EOF3 | with_common_indent 1
+			Add: [-std=c++${CXX_STD_VER}]
+EOF3
 	}
+)
+}
+EOF2
+})
+		target_link_libraries($target
+$({
+		$IS_FTXUI && cat << EOF2 | with_common_indent 1
+			PRIVATE ftxui::screen
+			PRIVATE ftxui::dom
+			PRIVATE ftxui::component
+EOF2
+})
+$({
+		$IS_NCURSES && cat << EOF2 | with_common_indent 1
+			${CURSES_LIBRARIES}
+EOF2
+})
+		)
+EOF
 }
 
-is_empty () {
-	! [[ "$@" ]] && {
-		return 0
-	}
+with_common_indent () {
+	local num_indents="$1"
+	local str
+	local str_tab_list
+	str="$(cat)"
+	str_tab_list=($(
+		echo "$str" |
+		sed -E 's/^(\t*).*/\1/g' |
+		tr '\t' '-'
+	))
+	local least_num_indents=${#str_tab_list[0]}
+	for str_tab in "${str_tab_list[@]}"; do
+		least_num_indents=$(math_min ${#str_tab} $least_num_indents)
+	done
+
+	cur_common_indent=$(
+		for i in $(seq 1 $least_num_indents); do
+			echo -n '\t'
+		done
+	)
+
+	new_common_indent=$(
+		for i in $(seq 1 $num_indents); do
+			echo -n '\t'
+		done
+	)
+
+	echo "$str" |
+		sed "s/^$cur_common_indent/$new_common_indent/g"
 }
 
-reset () {
-	in_dir=$1; shift
-	out_dir=$1; shift
-	prev_dir=$1; shift
-	exclude_dir=$1; shift
-	final_path=$1; shift
-	out_paths=$(get_paths_with_ext o $out_dir)
-	prev_paths=$(get_paths_with_ext prev $prev_dir)
-	paths="$out_paths $prev_paths $final_path"
-	show "deleting '$(eval echo $paths)'"
-	rm $paths
+math_min () {
+	local num1=$1
+	local num2=$2
+	if ((num1 < num2)); then
+		echo $num1
+	else
+		echo $num2
+	fi
 }
 
-#reset "$@"
+make_open_config () {
+	local open_config_path="$1"
+
+	if [[ ! -f "$open_config_path" ]]; then
+		get_open_config > "$open_config_path"
+	fi
+
+	local open_config_str
+
+	open_config_str=$(for i in $(seq 1 "$(get_open_config | wc -l)"); do
+		local line
+		line=$(get_open_config | get_line "$i") 
+		local var_part
+		var_part=$(echo "$line" | get_var_part)
+		local val_part
+		val_part=$(echo "$var_part" | get_value_in "$open_config_path")
+		if [[ "$val_part" == "" ]]; then
+			echo "$line"
+		else
+			echo "$val_part" | prefix "${var_part}="
+		fi
+	done)
+
+	echo "$open_config_str" > "$open_config_path"
+}
+
+get_line () {
+	sed -n "$1p"
+}
+
+get_var_part () {
+	sed -n "/^[^ ]\+=[^ ]*$/p" | sed -E "s/^(.*)=.*$/\1/"
+}
+
+get_value_in () {
+	local piped
+	piped="$(cat)"
+	cat "$1" | sed -n "/^${piped}\+=[^ ]*$/p" | sed -E "s/${piped}=(.*)$/\1/"
+}
+
+prefix () {
+	echo "$1$(cat)"
+}
+
 main "$@"
